# Generated by Django 4.1.7 on 2023-04-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_post_blog_post_publish_bb7600_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created"], name="blog_commen_created_0e6ed4_idx"
            ),
        ),
    ]
